language: node_js
sudo: false
node_js:
  - "node"
cache:
  directories:
  - keys
  - bower_components
  
before_install:
- npm install --quiet -g npm bower-installer
- chmod +x ./scripts/*.sh 

script:
- bower-installer
- ./scripts/build.sh 

after_success:
- ./scripts/deploy.sh
