language: node_js
sudo: false
node_js:
  - "node"
cache:
  directories:
  - keys
  - node_modules
  - bower_components

before_install:
- npm install --quiet -g npm bower-installer

script:
- bower-installer
- ./scripts/build.sh

after_success:
- ./scripts/deploy.sh
